name: Lint and test PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.dev.txt

    - name: Lint
      run: |
        black --check .
        flake8 .

    - name: Test
      run: nosetests .
