name: Publish new package version to PyPI

on:
  push:
    tags:
      - v*

jobs:
  publish_new_version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.build.txt

    - name: Lint
      run: |
        black --check .
        flake8 .

    - name: Test
      run: nosetests .

    - name: Build
      run: |
        python -m build
        echo -e "\nFiles in package:"
        tar tzf $(find dist -iname '*.tar.gz')

    - name: Upload
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        twine check dist/*
        twine upload --non-interactive dist/*
